apiVersion: apps/v1
kind: Deployment
metadata:
  name: securecodebox-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: securecodebox-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: securecodebox-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: securecodebox-controller-manager
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: docker.pkg.github.com/secureCodeBox/secureCodeBox-v2-alpha/operator:latest
          name: manager
          env:
            # TODO: integrate with cert manager and auto gen a cert for minio
            - name: S3_USE_SSL
              value: 'false'
            - name: S3_ENDPOINT
              value: "{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local"
            - name: S3_PORT
              value: '9000'
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-minio"
                  key: accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-minio"
                  key: secretkey
            - name: S3_BUCKET
              value: {{ .Values.minio.defaultBucket.name }}
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
