apiVersion: 'scans.experimental.securecodebox.io/v1'
kind: ScanTemplate
metadata:
  name: 'ssh-scan'
spec:
  name: 'ssh-scan'
  extractResults:
    type: ssh-scan-json
    location: '/home/securecodebox/ssh-scan-results.json'
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ssh-scan
              image: mozilla/ssh_scan
              command:
                - '/app/bin/ssh_scan'
                - '--output'
                - '/home/securecodebox/ssh-scan-results.json'
