apiVersion: 'execution.experimental.securecodebox.io/v1'
kind: ScanType
metadata:
  name: 'sslyze'
spec:
  extractResults:
    type: sslyze-json
    location: '/home/securecodebox/sslyze-results.json'
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: sslyze
              image: nablac0d3/sslyze@sha256:591d8626c7952788d5aa3946a60146d039c1582bc31aea6f9989500ebb5cc222
              command:
                - 'sslyze'
                - '--json_out'
                - '/home/securecodebox/sslyze-results.json'
              resources:
                {{- toYaml .Values.scannerJob.resources | nindent 16 }}
