apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "persistence-elastic.fullname" . }}
  labels:
    {{- include "persistence-elastic.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "persistence-elastic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "persistence-elastic.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTICSEARCH_ADDRESS
              # ElasticSearch Service Name seems to be independent from the release name...
              value: 'http://elasticsearch-master:9200'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
