apiVersion: "execution.experimental.securecodebox.io/v1"
kind: PersistenceProvider
metadata:
  name: "persistence-elastic"
  labels:
    type: Structured
spec:
  image: "scbexperimental/persistence-elastic:latest"
  env:
    - name: ELASTICSEARCH_ADDRESS
      value: "http://elasticsearch-master.{{ .Release.Namespace }}.svc.cluster.local:9200"
