apiVersion: "execution.experimental.securecodebox.io/v1"
kind: PersistenceProvider
metadata:
  name: {{ include "persistence-elastic.fullname" . }}
  labels:
    type: Structured
spec:
  image: "scbexperimental/persistence-elastic:latest"
  env:
{{- if .Values.externalElasticStack.enabled }}
    - name: ELASTICSEARCH_ADDRESS
      value: {{ .Values.externalElasticStack.elasticsearchAddress | quote }}
{{- else }}
    - name: ELASTICSEARCH_ADDRESS
      value: "http://elasticsearch-master.{{ .Release.Namespace }}.svc.cluster.local:9200"
{{- end }}
{{- if and .Values.authentication.user.username .Values.authentication.user.password }}
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: {{ include "persistence-elastic.fullname" . }}
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ include "persistence-elastic.fullname" . }}
          key: password
{{- else if and .Values.authentication.apiKey.id .Values.authentication.apiKey.key }}
    - name: ELASTICSEARCH_APIKEY_ID
      valueFrom:
        secretKeyRef:
          name: {{ include "persistence-elastic.fullname" . }}
          key: apiKey
    - name: ELASTICSEARCH_APIKEY
      valueFrom:
        secretKeyRef:
          name: {{ include "persistence-elastic.fullname" . }}
          key: apiKeyId
{{- end }}