{{- if or .Values.authentication.user.username .Values.authentication.user.password .Values.authentication.apiKey.key .Values.authentication.apiKey.id }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "persistence-elastic.fullname" . }}
type: Opaque
data:  
{{- if and .Values.authentication.user.username .Values.authentication.user.password  }}
  username: {{ .Values.authentication.user.username | b64enc | quote }}
  password: {{ .Values.authentication.user.password | b64enc | quote }}
{{- end }}
{{- if and .Values.authentication.apiKey.key .Values.authentication.apiKey.id  }}
  apiKey: {{ .Values.authentication.apiKey.key | b64enc | quote }}
  apiKeyId: {{ .Values.authentication.apiKey.id | b64enc | quote }}
{{- end }}
{{- end }}