version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 300
  method-lines:
    config:
      threshold: 50
exclude_patterns:
- "**/__testFiles__/"
- "**/__snapshots__/"
- "**/*.test.js"

