apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "screenshooter"
spec:
  extractResults:
    type: screenshot-png
    location: "/home/securecodebox/screenshot.png"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: screenshooter
              image: j12934/gowitness
              command:
                - "sh"
                - "/wrapper.sh"
                - "single"
                - "--disable-db"
                - "--destination"
                - "/home/securecodebox/"
                - "--output"
                - "screenshot.png"
