# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: scbexperimental/engine
  pullPolicy: Always

# Create PersistenceProvider CRD
createCRDs: true

redis:
  cluster:
    slaveCount: 0
    enabled: false

minio:
  defaultBucket:
    enabled: true
    name: securecodebox

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
