# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

legacyengine:
  address: "https://legacy-engine"
  scannerUser:
    username: ''
    password: ''
newengine:
  address: "http://engine:3000"

image:
  repository: scbexperimental/persistence-legacy-scb
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
