apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "trivy-json"
spec:
  handlesResultsType: trivy-json
  image: "{{ .Values.parserImage.registry }}/{{ .Values.parserImage.repository }}:{{ .Values.parserImage.tag }}"
