apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "trivy"
spec:
  name: "trivy"
  extractResults:
    type: trivy-json
    location: "/home/securecodebox/trivy-results.json"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trivy
              image: aquasec/trivy:0.6.0@sha256:61d42dbc030001463048f2f59fa034310fc114c7dee90b9dd9a9e3765dea7f5e
              command:
                - "trivy"
                - "--format"
                - "json"
                - "--output"
                - "/home/securecodebox/trivy-results.json"
