# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

engineURL: 'http://engine.default.svc.cluster.local:3000'
dispatcherEnvironmentName: 'cluster-name'

image:
  repository: scbexperimental/dispatcher
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
