apiVersion: v1
kind: ServiceAccount
metadata:
  name: lurcher
  labels:
{{ include "dispatcher.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: lurcher
  labels:
{{ include "dispatcher.labels" . | nindent 4 }}
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lurcher
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "dispatcher.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: lurcher
roleRef:
  kind: Role
  name: lurcher
  apiGroup: rbac.authorization.k8s.io