# permissions for end users to view hosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: host-viewer-role
rules:
- apiGroups:
  - targets.experimental.securecodebox.io
  resources:
  - hosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - targets.experimental.securecodebox.io
  resources:
  - hosts/status
  verbs:
  - get
