# permissions to do viewer parsedefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parsedefinition-viewer-role
rules:
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - parsedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - parsedefinitions/status
  verbs:
  - get
