# permissions to do edit parsedefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parsedefinition-editor-role
rules:
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - parsedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - parsedefinitions/status
  verbs:
  - get
  - patch
  - update
