# permissions to do viewer persistenceproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: persistenceprovider-viewer-role
rules:
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - persistenceproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - persistenceproviders/status
  verbs:
  - get
