apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dispatcher.fullname" . }}
  labels:
    {{- include "dispatcher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dispatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dispatcher.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: 'dispatcher'
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENGINE_ADDRESS
              value: {{ .Values.engineURL | quote }}
            - name: DISPATCHER_ENVIRONMENT_NAME
              value: {{ .Values.dispatcherEnvironmentName}}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
