apiVersion: v1
kind: ServiceAccount
metadata:
  name: 'dispatcher'
  labels:
{{ include "dispatcher.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: 'dispatcher'
  labels:
{{ include "dispatcher.labels" . | nindent 4 }}
rules:
  - apiGroups: ['experimental.securecodebox.io']
    resources: ['scanjobdefinitions', 'parsejobdefinitions']
    verbs: ['get', 'list']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['get', 'create', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'dispatcher'
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "dispatcher.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: dispatcher
roleRef:
  kind: Role
  name: dispatcher
  apiGroup: rbac.authorization.k8s.io