{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dispatcher.fullname" . }}
  labels:
    {{- include "dispatcher.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "dispatcher.selectorLabels" . | nindent 4 }}
{{- end }}