---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'persistence-elastic'
  labels:
    app: 'persistence-elastic'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 'persistence-elastic'
  template:
    metadata:
      labels:
        app: persistence-elastic
        app.kubernetes.io/name: 'persistence-elastic'
    spec:
      containers:
        - name: persistence-elastic
          image: scbexperimental/persistence-elastic
          imagePullPolicy: Always
          env:
            - name: ELASTICSEARCH_ADDRESS
              value: 'http://elasticsearch-master:9200'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: persistence-elastic
  name: persistence-elastic
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: persistence-elastic
