# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: scbexperimental/persistence-elastic
  pullPolicy: Always

# Enable this when you already have an Elastic Stack running to which you want to send your results
externalElasticStack:
  enabled: false
  elasticsearchAddress: "https://elasticsearch.example.com"
  kibanaAddress: "https://kibana.example.com"

# Configure authentication schema and credentials the persistence provider should use to connect to elasticsearch
# user and apikey are mutually exclusive, only set one!
authentication:
  user:
    username: null
    password: null
  apikey:
    # Todo(@J12934) figure out when the "id" field is required for api keys.
    key: null

elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  # image: docker.elastic.co/elasticsearch/elasticsearch-oss

kibana:
  enabled: true
  # image: docker.elastic.co/kibana/kibana-oss

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
