apiVersion: 'experimental.securecodebox.io/v1'
kind: ScanJobDefinition
metadata:
  name: 'example'
spec:
  extractResults:
    - type: example-json
      location: '/home/securecodebox/example-results.json'
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nmap
              image: scbexperimental/example:v42
              command: ['example', '--json', '/home/securecodebox/example-results.json']
