# permissions for end users to edit containerimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerimage-editor-role
rules:
- apiGroups:
  - targets.experimental.securecodebox.io
  resources:
  - containerimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - targets.experimental.securecodebox.io
  resources:
  - containerimages/status
  verbs:
  - get
