apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lurcher
  namespace: default
subjects:
  - kind: ServiceAccount
    name: lurcher
roleRef:
  kind: Role
  name: lurcher
  apiGroup: rbac.authorization.k8s.io
