# permissions for end users to edit parsedefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parsedefinition-editor-role
rules:
- apiGroups:
  - execution.experimental.securecodebox.io
  resources:
  - parsedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - execution.experimental.securecodebox.io
  resources:
  - parsedefinitions/status
  verbs:
  - get
