
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - watch
- apiGroups:
  - rbac
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - watch
- apiGroups:
  - rbac
  resources:
  - roles
  verbs:
  - create
  - get
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - parsedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - persistenceproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - scans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - scans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - scantemplates
  verbs:
  - get
  - list
  - watch
