# permissions for end users to edit scheduledscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledscan-editor-role
rules:
- apiGroups:
  - execution.experimental.securecodebox.io
  resources:
  - scheduledscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - execution.experimental.securecodebox.io
  resources:
  - scheduledscans/status
  verbs:
  - get
