# permissions to do edit targets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: target-editor-role
rules:
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - targets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - targets/status
  verbs:
  - get
  - patch
  - update
