# permissions to do viewer targets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: target-viewer-role
rules:
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - targets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scans.experimental.securecodebox.io
  resources:
  - targets/status
  verbs:
  - get
