apiVersion: "cascading.experimental.securecodebox.io/v1"
kind: CascadingRule
metadata:
  name: "https-tls-scan"
  labels:
    securecodebox.io/invasive: non-invasive
    securecodebox.io/intensive: light
spec:
  matches:
    anyOf:
      - category: "Open Port"
        attributes:
          port: 443
      - category: "Open Port"
        attributes:
          service: "https"
  scanSpec:
    scanType: "sslyze"
    parameters: ["--regular", "{{attributes.hostname}}:{{attributes.port}}"]
