apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    description: ImperativeCombinedScansHook needs to have the rights to create new scans and the usual patch rules to update the scan status
  name: imperative-combined-scans
  namespace: {{ .Release.Namespace }}
