apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "amass-jsonl"
spec:
  handlesResultsType: amass-jsonl
  image: "{{ .Values.parserImage.registry }}/{{ .Values.parserImage.repository }}:{{ .Values.parserImage.tag }}"
