---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: 'scb-dispatcher'
  labels:
    app: 'scb-dispatcher'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 'scb-dispatcher'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'scb-dispatcher'
    spec:
      serviceAccountName: scb-dispatcher
      containers:
        - name: scb-dispatcher
          image: scbexperimental/dispatcher
          imagePullPolicy: Always
          env:
            - name: ENGINE_ADDRESS
              value: http://engine.default.svc.cluster.local:3000
            - name: DISPATCHER_ENVIRONMENT_NAME
              value: do-fra1-scb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scb-dispatcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: scb-dispatcher
rules:
  - apiGroups: ['experimental.securecodebox.io']
    resources: ['scanjobdefinitions', 'parsejobdefinitions']
    verbs: ['get', 'list']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['get', 'create', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scb-dispatcher
  namespace: default
subjects:
  - kind: ServiceAccount
    name: scb-dispatcher
roleRef:
  kind: Role
  name: scb-dispatcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lurcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: lurcher
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lurcher
  namespace: default
subjects:
  - kind: ServiceAccount
    name: lurcher
roleRef:
  kind: Role
  name: lurcher
  apiGroup: rbac.authorization.k8s.io
