apiVersion: v2
name: nmap-subsequent-scans
description: Starts possible subsequent security scans based on nmap findings with open ports.

type: application

version: 0.1.0

appVersion: latest

dependencies: []
