apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScanCompletionHook
metadata:
  name: {{ include "persistence-elastic.fullname" . }}
  labels:
    type: Structured
spec:
  type: ReadOnly
  image: "scbexperimental/persistence-elastic:latest"
  {{- if .Values.image.digest }}
  image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}@{{ .Values.image.digest }}"
  {{- else }}
  image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  {{- end }}
  env:
    - name: ELASTICSEARCH_INDEX_PREFIX
      value: {{ .Values.indexPrefix | quote }}
{{- if .Values.externalElasticStack.enabled }}
    - name: ELASTICSEARCH_ADDRESS
      value: {{ .Values.externalElasticStack.elasticsearchAddress | quote }}
{{- else }}
    - name: ELASTICSEARCH_ADDRESS
      value: "http://elasticsearch-master.{{ .Release.Namespace }}.svc.cluster.local:9200"
{{- end }}
{{- if .Values.authentication.userSecret }}
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: {{ .Values.authentication.userSecret }}
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.authentication.userSecret }}
          key: password
{{- else if .Values.authentication.apiKeySecret }}
    - name: ELASTICSEARCH_APIKEY_ID
      valueFrom:
        secretKeyRef:
          name: {{ .Values.authentication.apiKeySecret }}
          key: apiKey
    - name: ELASTICSEARCH_APIKEY
      valueFrom:
        secretKeyRef:
          name: {{ .Values.authentication.apiKeySecret }}
          key: id
{{- end }}