apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "trivy"
spec:
  name: "trivy"
  extractResults:
    type: trivy-json
    location: "/home/securecodebox/trivy-results.json"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trivy
              image: aquasec/trivy:0.9.1@sha256:5020dac24a63ef4f24452a0c63ebbfe93a5309e40f6353d1ee8221d2184ee954
              command:
                - "trivy"
                # Suppress progress bar, as it pollutes non interactive terminal logs
                - "--no-progress"
                - "--format"
                - "json"
                - "--output"
                - "/home/securecodebox/trivy-results.json"
              resources:
                {{- toYaml .Values.scannerJob.resources | nindent 16 }}
