apiVersion: 'scans.experimental.securecodebox.io/v1'
kind: ParseDefinition
metadata:
  name: 'amass-jsonl'
spec:
  handlesResultsType: amass-jsonl
  image: docker.pkg.github.com/securecodebox/securecodebox-v2-alpha/amass-parser
