apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScanCompletionHook
metadata:
  name: {{ include "declarative-subsequent-scans.fullname" . }}
spec:
  type: ReadOnly
  {{- if .Values.image.registry }}
  {{- if .Values.image.digest }}
  image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}@{{ .Values.image.digest }}"
  {{- else }}
  image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  {{- end }}
  {{- else }}
  {{- if .Values.image.digest }}
  image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
  {{- else }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  {{- end }}
  {{- end }}