---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeaudit
  namespace: {{ .Release.Namespace}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubeaudit
  namespace: {{ .Release.Namespace}}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubeaudit
  namespace: {{ .Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: kubeaudit
    namespace: {{ .Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeaudit
