apiVersion: batch/v1
kind: Job
metadata:
  name: lurcher-test
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: primary
          image: alpine
          command: ["sleep", "30"]
        - name: lurcher
          image: scbexperimental/lurcher:go-version
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lurcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "default"
  name: lurcher
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lurcher
  namespace: default
subjects:
  - kind: ServiceAccount
    name: lurcher
roleRef:
  kind: Role
  name: lurcher
  apiGroup: rbac.authorization.k8s.io
