parserImage:
  registry: docker.io
  repository: scbexperimental/parser-test-scan
  tag: latest
# scannerJob:
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "250m"
#     limits:
#       memory: "512Mi"
#       cpu: "500m"
