apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
    {{- include "engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "engine.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: 'engine'
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: "engine-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: engine-redis
                  key: redis-password
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: S3_ENDPOINT
              value: "engine-minio.{{ .Release.Namespace }}.svc.cluster.local"
            - name: S3_TLS_ENABLED
              value: 'false'
            - name: S3_PORT
              value: '9000'
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: engine-minio
                  key: accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: engine-minio
                  key: secretkey
            - name: S3_BUCKET
              value: 'securecodebox'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
