apiVersion: v1
kind: Service
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
    {{- include "engine.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    {{- include "engine.selectorLabels" . | nindent 4 }}