parserImage:
  registry: docker.io
  repository: scbexperimental/parser-zap
  tag: latest
# scannerJob:
#   resources:
#     requests:
#       memory: "2Gi"
#       cpu: "250m"
#     limits:
#       memory: "2Gi"
#       cpu: "500m"
