apiVersion: v2
name: operator
description: secureCodeBox Operator to automate the execution of security scans on kubernetes

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.17.0

dependencies:
  - name: minio
    version: 5.0.19
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: minio.enabled
