# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# telemetryEnabled -- The Operator sends anonymous telemetry data, to give the team an overview how much the secureCodeBox is used. Find out more at https://www.securecodebox.io/telemetry
telemetryEnabled: true

image:
  registry: docker.io
  repository: scbexperimental/operator
  tag: latest
  digest: null
  pullPolicy: Always

lurcher:
  image:
    registry: docker.io
    repository: scbexperimental/lurcher
    tag: null
    digest: "sha256:0e9f18f85809fb8c042543657d340949db14e81fc727bf9fab4421befd317850"
    pullPolicy: IfNotPresent

minio:
  enabled: true
  defaultBucket:
    enabled: true
    name: "securecodebox"

# Config for external s3 systems
# enable this and disable minio if you want to directly connect agains AWS S3, Google Cloud Storage, DigitalOcean Spaces etc.
s3:
  enabled: false
  endpoint: "fra1.digitaloceanspaces.com"
  bucket: "my-bucket"
  # Implicit 443. You probably only need to change this when the system uses a non default port
  port: null
  # Name to a k8s secret with 'accesskey' and 'secretkey' as attributes in the same namespace as this release
  # Example creation via kubectl:
  # kubectl create secret generic my-secret --from-literal=accessKey="******" --from-literal=secretKey="******"
  keySecret: my-secret

#
# Config for the operator ressource limits
#
resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi
