# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: docker.io
  repository: scbexperimental/operator
  tag: latest
  digest: null
  pullPolicy: Always

lurcher:
  image:
    registry: docker.io
    repository: scbexperimental/lurcher
    tag: null
    digest: "sha256:0e9f18f85809fb8c042543657d340949db14e81fc727bf9fab4421befd317850"
    pullPolicy: IfNotPresent

s3:
  enabled: false
  endpoint: "fra1.digitaloceanspaces.com"
  bucket: "my-bucket"
  # Name to a k8s secret with 'accesskey' and 'secretkey' as attributes in the same namespace as this release
  # Example creation via kubectl:
  # kubectl create secret generic my-secret --from-literal=accessKey="******" --from-literal=secretKey="******"
  keySecret: my-secret

minio:
  enabled: true
  defaultBucket:
    enabled: true
    name: "securecodebox"
