# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: docker.io
  repository: scbexperimental/operator
  tag: latest
  digest: null
  pullPolicy: Always

lurcher:
  image:
    registry: docker.io
    repository: scbexperimental/lurcher
    tag: null
    digest: "sha256:0e9f18f85809fb8c042543657d340949db14e81fc727bf9fab4421befd317850"
    pullPolicy: IfNotPresent

s3:
  # TODO: Needs to be implemented
  # by default uses a locally installed minio instance.
  # this field can be used to directly configure s3 or a other api compatible service
  enabled: false
  endpoint: ""
  accessKey: ""
  secretKey: ""
  bucket: ""

minio:
  enabled: true
  defaultBucket:
    enabled: true
    name: "securecodebox"