apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "nmap"
spec:
  extractResults:
    type: nmap-xml
    location: "/home/securecodebox/nmap-results.xml"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nmap
              image: scbexperimental/nmap:7.80
              command: ["nmap", "-oX", "/home/securecodebox/nmap-results.xml"]
              securityContext:
                privileged: false
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                runAsUser: 1000
                runAsGroup: 3000
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - all
              resources:
                {{- toYaml .Values.scannerJob.resources | nindent 16 }}
