on: push
name: 'CI'
jobs:
  operator:
    name: 'Operator'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Run tests'
        run: |
          cd operator/
          make test
      - name: "Build'n Push Operator"
        uses: docker://j12934/one-click-docker@sha256:c0c3c90aa2fe65c0ffad0cf892aec9ea4dcc4731c1b2ccc0f3d4c8eacc4fb917
        env:
          DOCKER_IMAGE_NAME: operator
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_NAMESPACE: j12934/securecodebox
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./operator/
  lurcher:
    name: 'Lurcher'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Build'n Push Lurcher"
        uses: docker://j12934/one-click-docker@sha256:c0c3c90aa2fe65c0ffad0cf892aec9ea4dcc4731c1b2ccc0f3d4c8eacc4fb917
        env:
          DOCKER_IMAGE_NAME: lurcher
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_NAMESPACE: j12934/securecodebox
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./lurcher/
  integrations:
    name: 'Scanner Integrations'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Install npm dependencies in all parser subprojects'
        run: |
          for dir in /integrations/*/parser/
          do
              echo $dir
          done
