on: push
name: "CI"
jobs:
  integrations:
    name: "Test / Node.js Code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "list files and folders"
        run: ls
      - name: "Install npm dependencies in all parser sub projects"
        run: |
          for dir in integrations/*/parser/
          do
              cd $dir
              if [ -f package.json ] && [ -f package-lock.json ]; then
                  echo "Installing dependencies for $dir"
                  npm ci
              fi
              # cd back
              cd -
          done
      - name: "Install npm dependencies in all persistence sub projects"
        run: |
          for dir in persistence/*/
          do
              cd $dir
              if [ -f package.json ] && [ -f package-lock.json ]; then
                  echo "Installing dependencies for $dir"
                  npm ci
              fi
              # cd back
              cd -
          done
      - name: "Install npm test dependencies"
        run: |
          npm ci
          cd integrations/
          npm ci
      - name: "Run tests"
        run: |
          npm test -- --ci --colors --coverage
  operator:
    name: "Build / Operator"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2-beta
        with:
          go-version: "1.13"
      - name: "Lint Operator Go Code"
        run: |
          cd operator/
          go fmt ./...
          go vet ./...
      - name: "Build'n Push Operator"
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/operator
          tag_with_ref: true
          path: ./operator/
  lurcher:
    name: "Build / Lurcher"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2-beta
        with:
          go-version: "1.13"
      - name: "Lint Lurcher Go Code"
        run: |
          cd operator/
          go fmt ./...
          go vet ./...
      - uses: docker/build-push-action@v1
        name: "Build & Push Lurcher Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/lurcher
          tag_with_ref: true
          path: ./lurcher/
  parserImages:
    name: "Build / Parsers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # SDK
      - uses: docker/build-push-action@v1
        name: "Build & Push Parser SDK"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/parser-sdk-nodejs
          path: ./parser-sdk/nodejs/
          tag_with_ref: true
      # Actual Parsers
      - uses: docker/build-push-action@v1
        name: "Build & Push Amass Parser Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/parser-amass
          path: ./integrations/amass/parser/
          tag_with_ref: true
      - uses: docker/build-push-action@v1
        name: "Build & Push Nikto Parser Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/parser-nikto
          path: ./integrations/nikto/parser/
          tag_with_ref: true
      - uses: docker/build-push-action@v1
        name: "Build & Push Nmap Parser Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/parser-nmap
          path: ./integrations/nmap/parser/
          tag_with_ref: true
      - uses: docker/build-push-action@v1
        name: "Build & Push ssh_scan Parser Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/parser-ssh-scan
          path: ./integrations/ssh_scan/parser/
          tag_with_ref: true
      - uses: docker/build-push-action@v1
        name: "Build & Push SSLyze Parser Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/parser-sslyze
          path: ./integrations/sslyze/parser/
          tag_with_ref: true
      - uses: docker/build-push-action@v1
        name: "Build & Push OWASP Zap Parser Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/parser-zap
          path: ./integrations/zap/parser/
          tag_with_ref: true
  persistenceImages:
    name: "Build / PersistenceProviders"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # SDK
      - uses: docker/build-push-action@v1
        name: "Build & Push Persistence SDK"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/persistence-sdk-nodejs
          path: ./persistence-sdk/nodejs/
          tag_with_ref: true
      # Actual PersistenceProviders
      - uses: docker/build-push-action@v1
        name: "Build & Push Elastic PersistenceProvider Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/persistence-elastic
          path: ./persistence/persistence-elastic/
          tag_with_ref: true
      - uses: docker/build-push-action@v1
        name: "Build & Push Elastic PersistenceProvider Dashboard Importer Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/persistence-elastic-dashboard-importer
          path: ./persistence/persistence-elastic/dashboardImporter/
          tag_with_ref: true
  scannerImages:
    # Note we only build images for scanner that don't provider official public container images
    name: "Build / Scanner"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/build-push-action@v1
        name: "Build & Push Nmap Scanner Image"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: scbexperimental/nmap
          path: ./integrations/nmap/scanner/
          # Note: not prefixed with a "v" as this seems to match nmap versioning standards
          tags: "7.80,7.80-1,latest"
  integrationTests:
    name: "Test / Integration Tests"
    needs:
      - scannerImages
      - persistenceImages
      - parserImages
      - operator
      - lurcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Start kind cluster"
        run: |
          kind create cluster --image kindest/node:v1.18.0 --wait 3m
      - name: "Inspect kind cluster"
        run: | 
          kubectl config current-context
          kubectl get node
      - name: "Inspect Operator"
        run: | 
          kubectl create namespace securecodebox-system
          helm -n securecodebox-system install securecodebox-operator ./operator/ --wait
      - name: "Install Test Dependencies"
        run: |
          cd tests/integration/ 
          npm ci
      - name: "Nmap Integration Tests"
        run: | 
          kubectl apply -f integrations/nmap/nmap-scan-type.yaml -f integrations/nmap/nmap-parse-definition.yaml
          cd tests/integration/
          npx jest --ci --color nmap
      - name: "Delete kind cluster"
        run: | 
          kind delete cluster
