on: push
name: "CI"
jobs:
  operator:
    name: operator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build'n Push Engine
        uses: docker://j12934/one-click-docker@sha256:c0c3c90aa2fe65c0ffad0cf892aec9ea4dcc4731c1b2ccc0f3d4c8eacc4fb917
        env:
          DOCKER_IMAGE_NAME: operator
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_NAMESPACE: j12934/securecodebox
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./engine/
  lurcher:
    name: lurcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build'n Push Lurcher
        uses: docker://j12934/one-click-docker@sha256:c0c3c90aa2fe65c0ffad0cf892aec9ea4dcc4731c1b2ccc0f3d4c8eacc4fb917
        env:
          DOCKER_IMAGE_NAME: lurcher
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_NAMESPACE: j12934/securecodebox
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./lurcher/
